- name: Infrastructure Setup
  hosts: all
  become: yes
  collections:
    - company.infrastructure

  # vars:
  #     users: "{{ users_yaml | from_yaml if users_yaml is defined and users_yaml != '' else [] }}"
  vars:
    # Basic Configuration
    selected_disk_name: "sde"
    partition_strategy: "create_partition"
    split_disk: false
    partition_size_gb: 5
    
    # Volume Groups
    volume_group_name: "vg_app3"
    volume_group2_name: "vg_data3"
    
    # Primary VG Filesystem Configuration
    filesystem_config: |
      - path: "/var/www"
        size_mb: 2048
        fstype: "xfs"
      - path: "/opt/app"
        size_mb: 1024
        fstype: "ext4"
    
    # Secondary VG Filesystem Configuration
    filesystem_config2: |
      - path: "/data"
        size_mb: 3072
        fstype: "xfs"
      - path: "/backup"
        size_mb: 1024
        fstype: "ext4"
      
  tasks:
    - name: Setup LVM Management
      ansible.builtin.include_role:
        name: company.infrastructure.lvm_management
        
    # - name: Setup Java Management
    #   ansible.builtin.include_role:
    #     name: company.infrastructure.java_management

    # - name: Setup User Management
    #   ansible.builtin.include_role:
    #     name: company.infrastructure.user_management

