- name: Infrastructure Setup
  hosts: all
  become: yes
  collections:
    - company.infrastructure

  vars:
      users: "{{ users_yaml | from_yaml if users_yaml is defined and users_yaml != '' else [] }}"

  pre_tasks:
    - name: Discover available disks
      ansible.builtin.include_tasks: disk_discovery.yml
      when: auto_discover_disks | default(true)
      
  tasks:
    - name: Setup LVM Management
      ansible.builtin.include_role:
        name: company.infrastructure.lvm_management
        
    # - name: Setup Java Management
    #   ansible.builtin.include_role:
    #     name: company.infrastructure.java_management

    # - name: Setup User Management
    #   ansible.builtin.include_role:
    #     name: company.infrastructure.user_management
    #   when: users | length > 0
